# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Entertainment Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  entertainment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Entertainment Metric - YouTube, Chess, AniList
      - name: Entertainment Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: entertainment.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: anxlz
          template: classic
          base: ""
          config_octicon: yes
          config_timezone: Africa/Cairo
          config_twemoji: yes
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          
          plugin_anilist: yes
          plugin_anilist_limit: 10
          plugin_anilist_limit_characters: 22
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, characters
          plugin_anilist_shuffle: yes
          plugin_anilist_user: anxlz

          plugin_music: yes
          plugin_music_provider: youtube
          plugin_music_limit: 6
          plugin_music_playlist: >-
           https://music.youtube.com/playlist?list=PLJjv6Ya2rrv9b7ADpLu0vq9Xx6stjM5lI&si=BDNKBo7sEQd63D0T
           
          plugin_screenshot: yes
          plugin_screenshot_background: yes
          plugin_screenshot_mode: image
          plugin_screenshot_selector: body
          plugin_screenshot_title: Recent Project
          plugin_screenshot_url: https://egy-analyzer.vercel.app
          plugin_screenshot_viewport: '{"width": 1024, "height": 768}'
